### ISSUE TITLE
Error in `$<-.data.frame` with average.clean= sc.data.cleaning

### ISSUE THREAD

**Issue by hussghamlouch** [soumelis-lab/ICELLNET#13]
Hi there,
I am running a Seurat object through the ICELLNET pipeline however when I get to “average.clean=sc.data.cleaning” I get the following error:
> average.clean= sc.data.cleaning(object = seurat, db = db, filter.perc = filter.perc, save_file = T, path="C:/Users/", force.file = F)
**Error in `$<-.data.frame`(`*tmp*`, "Perc_posCell", value = NA) : 
  replacement has 1 row, data has 0**

> seurat
An object of class Seurat 
40987 features across 3877 samples within 2 assays 
Active assay: SCT (18784 features, 3000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap

As the active assay in Seurat object is SCT, I have added assay = “SCT” in the sc.data.cleaning function but I’ve got the same error: 
> average.clean= sc.data.cleaning(object = seurat, assay="SCT", db = db2, filter.perc = filter.perc, save_file = T, path="C:/Users/ ", force.file = F)
**Error in `$<-.data.frame`(`*tmp*`, "Perc_posCell", value = NA) : 
  replacement has 1 row, data has 0**

Could you please help with this?

Thanks,
Hussein

**Comment by lmassenet-regad** [comment]
Hello, 
Make sure you are using the latest version of ICELLNET (≥1.3.0) as this option (of using other assays than "RNA") has been implemented in the latest months. 

If yes, can you provide the outputs of the following commands:

**Comment by lmassenet-regad** [comment]
Hello,
Make sure you are using the latest version of ICELLNET (≥1.3.0) as this option (of using other assays than "RNA") has been implemented in the latest months.

If yes, can you provide the outputs of the following commands:  

```
head(seurat[["SCT"]]@data[,1:10]) 
intersect(rownames(seurat), unique(c(db$Ligand 1, db$Ligand 2)))  
sessionInfo()
```

**Comment by lmassenet-regad** [comment]
To help you troubleshooting, you will find below an exemple based on SCTransform tutorial where the sc.data.cleaning() function is working fine: 

`library(Seurat)
library(SeuratData)
library(patchwork)
library(dplyr)
library(ggplot2)
library(icellnet)

###### EXEMPLE

# install dataset
InstallData("ifnb")

# load dataset
LoadData("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")
ctrl <- ifnb.list[["CTRL"]]

# normalize and run dimensionality reduction on control dataset
ctrl <- SCTransform(ctrl, vst.flavor = "v2", verbose = FALSE) %>%
  RunPCA(npcs = 30, verbose = FALSE) %>%
  RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
  FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
  FindClusters(resolution = 0.7, verbose = FALSE)


# Prepare data for icellnet 
db2=db[1:100,] # test on smaller database to get faster 

data <- sc.data.cleaning(object = ctrl, db = db2,  assay = "SCT", filter.perc = 10, save_file = T, force.file = F, path= "~/Desktop/")
head(data)
`

**Comment by hussghamlouch** [comment]
Hello,
I reinstalled ICELLNET and this fixed the problem.
Thank you!
