### ISSUE TITLE
filter.perc for sc.data.cleaning()

### ISSUE THREAD

**Issue by mdidish** [soumelis-lab/ICELLNET#15]
Hello,
First of all, thank you for this useful package!

I have a question regarding the `filter.perc` argument for the `sc.data.cleaning()` function. In the function description you wrote:
```
If filter.perc is not NULL and set to 5, the gene expression matrix will be filtered to keep only gene filtering of the genes expressed in less than 5% of the cells at the cluster level. Other genes (filtered) will be set at 0 for the corresponding cluster(s).
```

Wouldn't it be the opposite? Keep only genes expressed in more than 5% of cells?

Best,
Marc

**Comment by lmassenet-regad** [comment]
Hello Marc, 
Thank you for the notice, you are absolutely right! I correct this asap.
Best,
Lucile
