### ISSUE TITLE
Scaling the data expression matrix

### ISSUE THREAD

**Issue by PieraccioliM** [soumelis-lab/ICELLNET#17]
Hi,
I used ICELLNET with bulk RNA-Seq data, but is not clear to me how to modify the n parameter for scaling gene expression matrix with my data. In the case study 1 tutorial (dissect intercellular commmunication of Cancer Associated Fibroblasts subsets) gene scaling of data was performed setting n = 18  in order to take the mean of the 5% extreme expression values as the maximum for partner cells.
How can I proceed to choose a correct value to assign to parameter n?
Thanks,
Marco

**Comment by lmassenet-regad** [comment]
Hello Marco, 
The n parameter of the gene.scaling function was added to limit the impact of outlier transcriptomic profiles when working with large number of samples. 
If you work with your own bulk RNAseq data, I would use n=1 at a first start. 
If you are using bulk RNAseq data for central data and the Human Primary Cell Atlas dataset for partner cells, then you can set n>1 as suggested in the tutorial (usually n= 0.05*number of partner cell samples considered). 
Please don't hesitate if it is still not clear or have other questions.
Lucile

**Comment by PieraccioliM** [comment]
Hi Lucille, 
could you please provide an example for the computation of the pvalue for the comparison of the communication scores obtained from central cells corresponding to different biological conditions with the same partner cells (between="conditions"), similarly to what you did for the between="cells" comparison ?
Thanks a lot
Marco
