### ISSUE TITLE
  object 'seurat.tum' not found

### ISSUE THREAD

**Issue by AtheerAS** [soumelis-lab/ICELLNET#18]
Hello,

I'm running into an error while using ICELLNET on Seurat object (version 4). Here is my code:

```
#Load seurat object
vedo <- readRDS("vedo_therapy/GSE228165_Vedo_merged_norm.rds")
Idents(vedo) <- vedo[['Monaco_BroadAnnots_FromFine']]

# Retrieve gene expression matrix
filter.perc=0
average.clean= sc.data.cleaning(object = vedo, db = db, filter.perc = filter.perc, save_file = T, path="path/", force.file = F)
```
When I ran this code, I got the following error:
```
[1] "Filling in intermediate table: percentage of expressing cell per cluster per gene, and mean of expression"

Error in Perc_exp_infos(object = seurat.tum, assay = assay, gene = as.character(data.int[i,  : 
  object 'seurat.tum' not found
```

Any hint? Thanks!

**Comment by lmassenet-regad** [comment]
Hi, 
Yes, this issue has normally been fixed in a recent minor update. Can you re-install the latest version (v2.1.2) ? It should normally work. Let me know.

**Comment by AtheerAS** [comment]
> Hi, Yes, this issue has normally been fixed in a recent minor update. Can you re-install the latest version (v2.1.2) ? It should normally work. Let me know.

Thanks, I'm actually using this version  (v2.1.2).

**Comment by lmassenet-regad** [comment]
@AtheerAS to be sure I understand: is it fixed for you now and can I close this issue ? 
Or you are encountering the error message "object 'seurat.tum' not found" using the version v2.1.2 ?

**Comment by AtheerAS** [comment]
> @AtheerAS to be sure I understand: is it fixed for you now and can I close this issue ? Or you are encountering the error message "object 'seurat.tum' not found" using the version v2.1.2 ?

I’m encountering the error while using version v2.1.2

**Comment by lmassenet-regad** [comment]
I corrected the sc.data.cleaning() function, thank you for noticing the issue. 
You can try with the latest version 2.2.0, hopefully it will work now. I suggest to restart the R session after installation, to be sure the update has been implemented.
Let me know.

If the problem persists after that, please print the result of the sessionInfo(), so that I can help. Thanks.
