### ISSUE TITLE
Downloading Human Primary Cell Atlas datasets 

### ISSUE THREAD

**Issue by eyleencorrales** [soumelis-lab/ICELLNET#5]
Hi,

Could you please advice me how to download PC.data.all and PC.target.all objects from the github? I cloned the repository, and then attempted `git lfs pull` to download the files, but I get the following error

```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                          
error: failed to fetch some objects from 'https://github.com/soumelis-lab/ICELLNET.git/info/lfs'
```

Thanks in advanced!

Eyleen

**Comment by lmassenet-regad** [comment]
Hi Eyleen,

Thanks for your message. PC.data.all and  PC.target.all objects are now normal csv files (are not stored with LFS anymore), so you should be able to clone or download the repository and open these objects. For purpose storage PC.data.all has been zipped and should be unzipped to read it as csv file.
Hope this helps, 
Kind regards, 

Lucile
