### ISSUE TITLE
Example1_CAF.md error in defining PC.target and PC.data

### ISSUE THREAD

**Issue by superman2412** [soumelis-lab/ICELLNET#6]
Hi, I am encountering an error. Could you please help me fix it? Thank you so  much!
Here's the code. 

`library(BiocGenerics)
library("org.Hs.eg.db")
library("hgu133plus2.db")
library(jetset)
library(ggplot2)
library(dplyr)
library(icellnet)
library(gridExtra)

db=as.data.frame(read.csv(curl::curl(url="https://raw.githubusercontent.com/soumelis-lab/ICELLNET/master/data/ICELLNETdb.tsv"), sep="\t",header = T, check.names=FALSE, stringsAsFactors = FALSE, na.strings = ""))
               
my.selection.LR=c("Cytokine")
db2 <- db[grepl(paste(my.selection.LR, collapse="|"),db$Classifications),] if you want to use all the database, do instead : db2=db
db2$Subfamily=db2$Cytokines to define subfamily of interest as cytokines. 
db.name.couple=name.lr.couple(db2, type="Subfamily")
head(db.name.couple)`

````{r}
download PC.data.all and PC.target.all objects from the github and open them on your Rstudio session - adapt path if needed
PC.data.all=as.data.frame(read.csv("../PC.data.all.csv", sep=",", header = T, check.names=FALSE, stringsAsFactors = FALSE, na.strings = ""))

rownames(PC.data.all)=PC.data.all$ID

PC.target.all=as.data.frame(read.csv("../PC.target.all.csv", sep=",",header = T, check.names=FALSE, stringsAsFactors = FALSE, na.strings = ""))

my.selection=c("Epith", "Fblast_B", "Endoth","Mono", "Macroph", "pDC", "DC2", "DC1", "NK", "Neutrop","CD4 T cell","CD8 T cell", "Treg","B cell")

````
`PC.target = PC.target.all[which(PC.target.all$Class%in%my.selection|PC.target.all$Class%in%my.selection),c("ID","Class","Cell_type")]
`
`Error in `[.data.frame`(PC.target.all, which(PC.target.all$Class %in% : undefined columns selected

3.
stop("undefined columns selected")

2.
`[.data.frame`(PC.target.all, which(PC.target.all$Class %in% my.selection | PC.target.all$Class %in% my.selection), c("ID", "Class", "Cell_type"))
1.

PC.target.all[which(PC.target.all$Class %in% my.selection | PC.target.all$Class %in% my.selection), c("ID", "Class", "Cell_type")]`

`PC.data = PC.data.all[,PC.target$ID]`

Error in `[.data.frame`(PC.data.all, , PC.target$ID) : object 'PC.target' not found

**Comment by lmassenet-regad** [comment]
Hi, 

You seems to have a problem creating PC.target from PC.target.all file.
Here are some ideas for troubleshooting: 

- Do you have any problems to read PC.target.all file ? (dimensions should be 745 by 11)
--> If not, here is a command to download it differently : 
`
PC.target.all=as.data.frame(read.csv( curl::curl(url="https://raw.githubusercontent.com/soumelis-lab/ICELLNET/master/data/PC.target.all.csv"), sep=",",header = T, check.names=FALSE, stringsAsFactors = FALSE, na.strings = ""))
`

- Is this the following command working ? (with your my.selection, should be a vector of 353 elements) 
`which(PC.target.all$Class%in%my.selection|PC.target.all$Cell_type%in%my.selection)`

Hope this helps, don't hesitate if you need further help,
Lucile

**Comment by sdey0309** [comment]
I'm getting the same error while running the second example

**Comment by lmassenet-regad** [comment]
Hi, 
This should usually come from columns names that are either not defined or not correctly defined. Check the column names of all your objects .
