### ISSUE TITLE
RDS file used in case study 2

### ISSUE THREAD

**Issue by sdey0309** [soumelis-lab/ICELLNET#8]
Is the Lupus_Seurat_SingleCell_Landscape.Rds file available to download? The data is not available in the links present in the paper.

**Comment by lmassenet-regad** [comment]
Dear sdey0309, 
The file is not directly available to download but we added the code to generate the file from the public data available :  https://github.com/soumelis-lab/ICELLNET/blob/master/Code_SeuratObject_Exemple2.md
